export {
  useMapViewModel,
  // Selector hooks
  useLivePosition,
  useFlightPhase,
  useETA,
  useWaypoints,
  useSigmets,
  useActiveAlerts,
  useIsTracking,
  useSyncStatus,
  useDeviationReport,
  useComparisonTab,
  useDownloadProgress,
  useEstimatedTrack,
  useActualTrack,
  useMapCamera,
  useScrubberPosition,
  useActiveFlight,
  useRemainingDistance,
} from './MapViewModel';

export type {
  MapViewModel,
  MapViewModelState,
  MapViewModelActions,
  LivePosition,
  LatLng,
  DownloadStep,
  DownloadStatus,
  DownloadProgress,
  SyncStatus,
  ComparisonTab,
  MapCamera,
  ActiveAlert,
} from './MapViewModel';